### ISSUE TITLE
AED not showing up

### ISSUE THREAD

**Issue by jxpsert** [openstreetmap-polska/openaedmap-frontend#110] opened 2022-12-28 16:00 UTC
Hi there! I've recently added [this](https://www.openstreetmap.org/node/10285213146) AED. However, it doesn't seem to be showing up on OpenAEDMap. Did I tag something incorrectly, or is this a bug on OpenAEDMap's side?

For reference - here's the location on [OpenAEDMap](https://openaedmap.org/#map=17/51.826612/5.867843)

**Comment by RicoElectrico** [comment] 2022-12-28 20:59
There's a bug in [OpenAEDmap backend ](https://github.com/openstreetmap-polska/openaedmap-backend) regarding tile expiry logic in  I've uncovered it earlier.
Even though the AED is in the database, it's not in the vector tiles.
Another example: https://openaedmap.org/#node_id=10280822109&map=17/52.323665/21.098454

**Comment by jxpsert** [comment] 2022-12-29 02:12
So, is there anything I can do about this, or should I just wait until a fix is implemented?

**Comment by RicoElectrico** [comment] 2022-12-29 23:08
We have to wait, unfortunately.

**Comment by jxpsert** [comment] 2022-12-29 23:26
Was this an issue with this tile, or all tiles? I've added some AED's in another town, but they don't show up either.

**Comment by ttomasz** [comment] 2022-12-30 01:30
> Was this an issue with this tile, or all tiles? I've added some AED's in another town, but they don't show up either.

It was global problem. I fixed one bug. You can check back in about 12 hours to see if the AED shows up on the map.

**Comment by jxpsert** [comment] 2022-12-30 13:51
Issue looks to be fixed!

**Comment by RicoElectrico** [comment] 2023-01-02 18:26
The issue is still present. Updates are still lagging behind.
Example: https://www.openstreetmap.org/node/10300322009 and https://openaedmap.org/#map=18/51.641145/17.130598 (not visible as of writing this comment 2023-02-01 19:26 CET)

**Comment by Fizzie41** [comment] 2023-07-10 22:16
Problem is still occurring.

Two that I added 3 weeks ago aren't yet appearing:
https://www.openstreetmap.org/node/10948443832
https://www.openstreetmap.org/node/10991230059

Both should be visible here: https://openaedmap.org/#map=14/-25.06627/148.25927. Other POIs that I added at the same time are visible, but not the AEDs.

**Comment by jxpsert** [comment] 2023-07-10 22:21
Reopening this based on @Fizzie41 's comment. Why/how is this still an issue?

**Comment by starsep** [comment] 2023-07-12 19:12
I believe the issue is in the processing on the backend. We don't know where exactly

**Comment by Fizzie41** [comment] 2023-07-12 22:24
Yes, there must be a problem somewhere? I've just tried a OT search for AEDs in Australia https://overpass-turbo.eu/s/1xkM which shows 258 of them, where you only have 244. For New Zealand, OT has 116 https://overpass-turbo.eu/s/1xkN vs 91. https://openaedmap.org/#map=3/-26.79/145

**Comment by rbovard** [comment] 2023-08-02 13:34
I can also confirm the problem: the defibrillators I've been adding for a month now no longer appear, whereas before they were visible in less than a day.

**Comment by Fizzie41** [comment] 2023-08-02 21:29
Thanks! Good to see that we helped find a hidden problem!

**Comment by starsep** [comment] 2023-08-07 22:12
This issue has been resolved by new backend.
Thanks @Zaczero for great work! :rocket:

**Closed by starsep** 2023-08-07 22:12 UTC
Labels: bug

**Comment by rbovard** [comment] 2023-08-08 06:20
Great, thanks a lot!

**Comment by Fizzie41** [comment] 2023-08-08 23:35
Thanks for fixing this, but a further question, thanks.

Existing AEDs show at zoom 6: https://openaedmap.org/#map=6/-26.162/151.623 , but the two I added don't appear till zoom 7: https://openaedmap.org/#map=7/-25.881/150.788 ?

Shouldn't they all appear at the same zoom level?

**Comment by Zaczero** [comment] 2023-08-08 23:55
> Thanks for fixing this, but a further question, thanks.
> 
> Existing AEDs show at zoom 6: https://openaedmap.org/#map=6/-26.162/151.623 , but the two I added don't appear till zoom 7: https://openaedmap.org/#map=7/-25.881/150.788 ?
> 
> Shouldn't they all appear at the same zoom level?

This displays properly for me. There can be up to 3 minutes cache difference on zoom levels >=6. I have also just deployed a new update which required ~30 mins maintenance during which tiles stopped updating. Maybe that's when you noticed this bug.

**Comment by Fizzie41** [comment] 2023-08-09 00:22
Thanks!

I had just cleared my cache when I saw that they weren't displaying at all, so that may be the issue.

I'll check it again later & report back.
